### ISSUE TITLE
how i can destroy this function ?

### ISSUE THREAD

**Issue by crawlynoob** [webmandesign/jquery.hoverdir#4]
how i can destroy this function ?

**Comment by webmandesign** [comment]
Hi,

Can you provide more info about what you mean please?

If you are using one of my WordPress themes, please note that I provide support for them at https://support.webmandesign.eu

Best regards,

Oliver

**Comment by crawlynoob** [comment]
hi! i want destroy hoverdir effect on small width display, judging by the code, this function is available, but I do not know how to use the syntax correctly

https://github.com/webmandesign/jquery.hoverdir/blob/master/jquery.hoverdir.js#L198

**Comment by webmandesign** [comment]
Hi,

Please note that this is a very old code I no longer maintain and it was derived from https://github.com/codrops/DirectionAwareHoverEffect as [mentioned in the code head](https://github.com/webmandesign/jquery.hoverdir/blob/master/jquery.hoverdir.js#L4).

However, please note that this particular code only applies CSS classes on the HTML elements. Any hoverdir effect is provided via your CSS. So to remove the effect on smaller screens it is much easier to tackle the CSS code.

Like I've mentioned if you are using one of my WordPress themes, please log a support ticket at https://support.webmandesign.eu where I will be able to provide you with more specific help.
Otherwise please check your CSS code to remove the effect for small screens. Or you can even fork this code and adapt it to your needs and use it on your project that way.

Best regards,

Oliver
